package com.francescoalessi.parla.api.model
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ModelInfoResponse(
    val result: ModelInfoResultData
)

@Serializable
data class ModelInfoResultData(
    val model_name: String,
    val lora_names: List<String>,
    @SerialName("shared.settings") val sharedSettings: ModelInfoSharedSettings,
    @SerialName("shared.args") val sharedArgs: ModelInfoSharedArgs
)

@Serializable
data class ModelInfoSharedSettings(
    val dark_theme: Boolean,
    val show_controls: Boolean,
    val start_with: String,
    val mode: String,
    val chat_style: String,
    val character: String,
    val prompt_default: String,
    val prompt_notebook: String,
    val preset: String,
    val max_new_tokens: Int,
    val max_new_tokens_min: Int,
    val max_new_tokens_max: Int,
    val seed: Int,
    val negative_prompt: String,
    val truncation_length: Int,
    val truncation_length_min: Int,
    val truncation_length_max: Int,
    val custom_stopping_strings: String,
    val auto_max_new_tokens: Boolean,
    val ban_eos_token: Boolean,
    val add_bos_token: Boolean,
    val skip_special_tokens: Boolean,
    val stream: Boolean,
    val name1: String,
    val name2: String,
    val context: String,
    val greeting: String,
    val instruction_template: String,
    val chat_instruct_command: String,
    val autoload_model: Boolean,
    val default_extensions: List<String>
)

@Serializable
data class ModelInfoSharedArgs(
    val notebook: Boolean,
    val chat: Boolean,
    val multi_user: Boolean,
    val character: String?,
    val model: String?,
    val lora: String?,
    val model_dir: String,
    val lora_dir: String,
    val model_menu: Boolean,
    val no_stream: Boolean,
    val settings: String?,
    val extensions: List<String>,
    val verbose: Boolean,
    val loader: String,
    val cpu: Boolean,
    val auto_devices: Boolean,
    val gpu_memory: Int?,
    val cpu_memory: Int?,
    val disk: Boolean,
    val disk_cache_dir: String,
    val load_in_8bit: Boolean,
    val bf16: Boolean,
    val no_cache: Boolean,
    val xformers: Boolean,
    val sdp_attention: Boolean,
    val trust_remote_code: Boolean,
    val load_in_4bit: Boolean,
    val compute_dtype: String,
    val quant_type: String,
    val use_double_quant: Boolean,
    val threads: Int,
    val n_batch: Int,
    val no_mmap: Boolean,
    val low_vram: Boolean,
    val mlock: Boolean,
    val mul_mat_q: Boolean,
    val cache_capacity: Int?,
    val n_gpu_layers: Int,
    val tensor_split: String,
    val n_ctx: Int,
    val llama_cpp_seed: Double,
    val n_gqa: Int,
    val rms_norm_eps: Int,
    val wbits: Int,
    val model_type: String?,
    val groupsize: Int,
    val pre_layer: String?,
    val checkpoint: String?,
    val monkey_patch: Boolean,
    val triton: Boolean,
    val no_inject_fused_attention: Boolean,
    val no_inject_fused_mlp: Boolean,
    val no_use_cuda_fp16: Boolean,
    val desc_act: Boolean,
    val disable_exllama: Boolean,
    val gpu_split: String,
    val max_seq_len: Int,
    val cfg_cache: Boolean,
    val deepspeed: Boolean,
    val nvme_offload_dir: String?,
    val local_rank: Int,
    val rwkv_strategy: String?,
    val rwkv_cuda_on: Boolean,
    val alpha_value: Int,
    val rope_freq_base: Int,
    val compress_pos_emb: Int,
    val listen: Boolean,
    val listen_host: String?,
    val listen_port: Int?,
    val share: Boolean,
    val auto_launch: Boolean,
    val gradio_auth: String?,
    val gradio_auth_path: String?,
    val ssl_keyfile: String?,
    val ssl_certfile: String?,
    val api: Boolean,
    val api_blocking_port: Int,
    val api_streaming_port: Int,
    val public_api: Boolean,
    val public_api_id: String?,
    val multimodal_pipeline: String?
)